#!/usr/bin/env python3
"""E2E test script for NRT MDM pipeline (TST-02).

Modes:
  --mode single      (default) Send 1 random update, show BEFORE/AFTER/CDC, exit.
  --mode continuous  Send 1 update/sec indefinitely, print latency stats.

Phase 1: Initial load from bulk CSV data (1,500 records) — skipped if DB already has data.
Phase 2: Send updates depending on mode.

Prerequisites:
  docker compose up -d  (postgres + kafka + mdm-engine must be running)
  shared/output/initial/ (generated by shared/scripts/generate_test_data.py)
"""

import argparse
import json
import os
import random
import subprocess
import sys
import time

import psycopg
from confluent_kafka import Consumer, Producer, KafkaError

# Connection defaults match docker-compose.yml
POSTGRES_DSN = os.environ.get("POSTGRES_DSN", "postgresql://mdm:mdm@localhost:5432/mdm")
KAFKA_BOOTSTRAP = os.environ.get("KAFKA_BOOTSTRAP_SERVERS", "localhost:19092")
GOLDEN_TOPIC = "topic.mdm.golden"
XREF_TOPIC = "topic.mdm.xref"


# ---------------------------------------------------------------------------
# Phase 1: Initial Load
# ---------------------------------------------------------------------------

def get_golden_count(conn) -> int:
    """Get count of current golden records."""
    with conn.cursor() as cur:
        cur.execute("SELECT COUNT(*) FROM golden_customers WHERE is_current = TRUE")
        return cur.fetchone()[0]


def get_source_count(conn) -> int:
    """Get count of source customer records."""
    with conn.cursor() as cur:
        cur.execute("SELECT COUNT(*) FROM source_customers")
        return cur.fetchone()[0]


def run_initial_load():
    """Run test_producer --mode replay to load bulk CSVs into Kafka."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)

    env = os.environ.copy()
    env["KAFKA_BOOTSTRAP_SERVERS"] = KAFKA_BOOTSTRAP

    result = subprocess.run(
        [sys.executable, "-m", "nrt_mdm.test_producer", "--mode", "replay"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=120,
    )
    if result.returncode != 0:
        print(f"  ERROR: replay failed: {result.stderr}")
        return False
    print(f"  {result.stdout.strip().split(chr(10))[-1]}")
    return True


def wait_for_golden_stable(conn, timeout: int = 180) -> int:
    """Wait for golden count to stabilize (consumer finished processing)."""
    prev_count = 0
    stable_ticks = 0
    deadline = time.time() + timeout

    while time.time() < deadline:
        count = get_golden_count(conn)
        if count == prev_count and count > 0:
            stable_ticks += 1
            if stable_ticks >= 3:
                return count
        else:
            stable_ticks = 0
        prev_count = count
        sys.stdout.write(f"\r  Golden records: {count} (waiting to stabilize...)")
        sys.stdout.flush()
        time.sleep(3)

    print()
    return prev_count


# ---------------------------------------------------------------------------
# Phase 2: Single Random Update
# ---------------------------------------------------------------------------

def pick_random_source(conn) -> dict | None:
    """Pick a random CRM_A source record that has a golden record.

    We pick CRM_A because it has highest survivorship priority,
    so updates to it always propagate to the golden record.
    """
    with conn.cursor() as cur:
        cur.execute("""
            SELECT sc.source_system, sc.source_key, sc.first_name, sc.last_name,
                   sc.email, sc.phone, cc.cluster_id
            FROM source_customers sc
            JOIN customer_clusters cc ON sc.source_system = cc.source_system AND sc.source_key = cc.source_key
            WHERE sc.source_system = 'CRM_A'
            ORDER BY RANDOM()
            LIMIT 1
        """)
        row = cur.fetchone()
    if row is None:
        return None
    return {
        "source_system": row[0],
        "source_key": row[1],
        "first_name": row[2],
        "last_name": row[3],
        "email": row[4],
        "phone": row[5],
        "cluster_id": row[6],
    }


def build_update_event(source_rec: dict) -> tuple[str, str, dict]:
    """Build an update event for a source record with a realistic change.

    Returns (topic, key, payload).
    """
    ss = source_rec["source_system"]
    key = source_rec["source_key"]

    # Always update email — CRM_A has highest priority so it always wins survivorship
    change = "email"

    new_email = source_rec["email"]
    new_phone = source_rec["phone"]
    new_first = source_rec["first_name"]
    new_last = source_rec["last_name"]

    if change == "email" and new_email:
        # Update email domain
        local = new_email.split("@")[0] if "@" in new_email else new_email
        new_email = f"{local}@updated-corp.com"
    elif change == "phone":
        # New phone number
        new_phone = f"+1{random.randint(200, 999)}{random.randint(1000000, 9999999)}"
    elif change == "name" and new_first:
        # Correct a name (add/fix)
        new_first = new_first.title() + "a"  # e.g., "Bill" -> "Billa" (simulates correction)

    if ss == "CRM_A":
        topic = "topic.crm.a"
        payload = {
            "src_customer_id": key,
            "first_name": new_first or "",
            "last_name": new_last or "",
            "email": new_email or "",
            "phone": new_phone or "",
        }
    elif ss == "CRM_B":
        topic = "topic.crm.b"
        name = f"{new_first or ''} {new_last or ''}".strip()
        payload = {
            "customer_key": key,
            "name": name,
            "email_address": new_email or "",
            "mobile": new_phone or "",
        }
    else:  # CRM_C
        topic = "topic.crm.c"
        caller_name = f"{new_first or ''} {new_last or ''}".strip()
        payload = {
            "ticket_customer_id": key,
            "caller_name": caller_name,
            "callback_email": new_email or "",
            "callback_phone": new_phone or "",
        }

    return topic, key, payload


def get_golden_for_cluster(conn, cluster_id: int) -> dict | None:
    """Get the current golden record for a cluster."""
    with conn.cursor() as cur:
        cur.execute("""
            SELECT first_name, last_name, email, phone, dq_score, source_count, row_hash
            FROM golden_customers
            WHERE cluster_id = %s AND is_current = TRUE
        """, (cluster_id,))
        row = cur.fetchone()
    if row is None:
        return None
    return {
        "cluster_id": cluster_id,
        "first_name": row[0],
        "last_name": row[1],
        "email": row[2],
        "phone": row[3],
        "dq_score": row[4],
        "source_count": row[5],
        "row_hash": row[6],
    }


def format_golden(g: dict | None) -> str:
    """Format a golden record for display."""
    if g is None:
        return "(none)"
    return (f"cluster={g['cluster_id']}: {g['first_name']} {g['last_name']} | "
            f"email={g['email']} | phone={g['phone']} | "
            f"dq={g['dq_score']} | sources={g['source_count']}")


# ---------------------------------------------------------------------------
# Continuous mode: loop with latency stats
# ---------------------------------------------------------------------------

def run_continuous(conn, rate: float = 1.0):
    """Send updates continuously, printing latency for each."""
    producer = Producer({"bootstrap.servers": KAFKA_BOOTSTRAP})
    latencies = []
    count = 0
    interval = 1.0 / rate

    print(f"\n  Continuous mode: {rate} update(s)/sec (Ctrl+C to stop)")
    print(f"  {'#':<5} {'Source':<20} {'Cluster':<8} {'Latency':>10} {'p50':>8} {'p95':>8} {'p99':>8}")
    print(f"  {'-'*5} {'-'*20} {'-'*8} {'-'*10} {'-'*8} {'-'*8} {'-'*8}")

    try:
        while True:
            source_rec = pick_random_source(conn)
            if source_rec is None:
                time.sleep(1)
                continue

            cluster_id = source_rec["cluster_id"]
            golden_before = get_golden_for_cluster(conn, cluster_id)

            topic, key, payload = build_update_event(source_rec)
            ts_ms = int(time.time() * 1000)
            producer.produce(topic, key=key, value=json.dumps(payload).encode(), timestamp=ts_ms)
            producer.flush()
            produce_time = time.time()

            # Poll until change detected
            for _ in range(50):  # max 5s
                time.sleep(0.05)
                golden_after = get_golden_for_cluster(conn, cluster_id)
                if golden_after and golden_after.get("row_hash") != (golden_before or {}).get("row_hash"):
                    break

            latency_ms = int((time.time() - produce_time) * 1000)
            latencies.append(latency_ms)
            count += 1

            # Compute percentiles
            s = sorted(latencies)
            p50 = s[len(s) // 2]
            p95 = s[int(len(s) * 0.95)]
            p99 = s[int(len(s) * 0.99)]

            source_label = f"{source_rec['source_system']}|{source_rec['source_key']}"
            print(f"  {count:<5} {source_label:<20} {cluster_id:<8} {latency_ms:>7}ms {p50:>5}ms {p95:>5}ms {p99:>5}ms")

            # Throttle
            elapsed = time.time() - produce_time
            if elapsed < interval:
                time.sleep(interval - elapsed)

    except KeyboardInterrupt:
        print(f"\n\n  Stopped after {count} updates")
        if latencies:
            s = sorted(latencies)
            print(f"  Latency: min={s[0]}ms  p50={s[len(s)//2]}ms  p95={s[int(len(s)*0.95)]}ms  max={s[-1]}ms")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="NRT MDM E2E Test")
    parser.add_argument("--mode", choices=["single", "continuous"], default="single",
                        help="single: 1 update + exit. continuous: loop with latency stats.")
    parser.add_argument("--rate", type=float, default=1.0,
                        help="Updates per second in continuous mode (default: 1.0)")
    args = parser.parse_args()

    print("=" * 70)
    print("NRT MDM E2E Test")
    print("=" * 70)

    # Connect to Postgres
    try:
        conn = psycopg.connect(POSTGRES_DSN)
        conn.autocommit = True
    except Exception as e:
        print(f"\n  FAIL: Cannot connect to Postgres: {e}")
        print("  Is docker compose running? Try: docker compose up -d")
        sys.exit(1)

    # =========================================================================
    # Phase 1: Initial Load
    # =========================================================================
    print("\n[Phase 1] Initial Load")
    golden_count = get_golden_count(conn)
    source_count = get_source_count(conn)

    if golden_count > 100:
        print(f"  Already loaded: {source_count} source records -> {golden_count} golden records")
    else:
        print("  Database is empty, loading bulk CSV data...")
        success = run_initial_load()
        if not success:
            print("  FAIL: Could not replay bulk data")
            sys.exit(1)

        print("  Waiting for MDM engine to process all records...")
        golden_count = wait_for_golden_stable(conn, timeout=180)
        print(f"\n  Initial load complete: {golden_count} golden records")

    if golden_count < 10:
        print("  FAIL: Insufficient golden records after initial load")
        sys.exit(1)

    # =========================================================================
    # Phase 2: Mode dispatch
    # =========================================================================
    if args.mode == "continuous":
        run_continuous(conn, rate=args.rate)
        sys.exit(0)

    # =========================================================================
    # Phase 2: Single Random Update
    # =========================================================================
    print("\n[Phase 2] Single Random Update")

    # Pick a random source record
    source_rec = pick_random_source(conn)
    if source_rec is None:
        print("  FAIL: No source records found")
        sys.exit(1)

    cluster_id = source_rec["cluster_id"]
    print(f"  Selected: {source_rec['source_system']}|{source_rec['source_key']} (cluster={cluster_id})")

    # Snapshot BEFORE
    golden_before = get_golden_for_cluster(conn, cluster_id)
    print(f"\n  --- Golden Record (BEFORE) ---")
    print(f"    {format_golden(golden_before)}")

    # Build update event
    topic, key, payload = build_update_event(source_rec)
    print(f"\n  --- Inbound Event ---")
    print(f"  [{topic}] key={key}")
    print(f"    {json.dumps(payload)}")

    # Subscribe CDC consumer before producing
    cdc_consumer = Consumer({
        "bootstrap.servers": KAFKA_BOOTSTRAP,
        "group.id": f"e2e-cdc-{int(time.time())}",
        "auto.offset.reset": "end",
        "enable.auto.commit": False,
    })
    cdc_consumer.subscribe([GOLDEN_TOPIC, XREF_TOPIC])
    for _ in range(5):
        cdc_consumer.poll(timeout=1.0)
    time.sleep(1)

    # Produce the single update
    producer = Producer({"bootstrap.servers": KAFKA_BOOTSTRAP})
    ts_ms = int(time.time() * 1000)
    producer.produce(topic, key=key, value=json.dumps(payload).encode(), timestamp=ts_ms)
    producer.flush()
    produce_time = time.time()
    print("\n  Produced 1 update event")

    # Poll until golden record changes (measure latency)
    print("  Waiting for processing...", end="", flush=True)
    golden_after = None
    for _ in range(50):  # max 5 seconds (50 x 100ms)
        time.sleep(0.1)
        golden_after = get_golden_for_cluster(conn, cluster_id)
        if golden_after and golden_after.get("row_hash") != (golden_before or {}).get("row_hash"):
            break
    latency_ms = int((time.time() - produce_time) * 1000)
    print(f" done ({latency_ms}ms)")

    # Snapshot AFTER
    golden_after = get_golden_for_cluster(conn, cluster_id)
    print(f"\n  --- Golden Record (AFTER) ---")
    print(f"    {format_golden(golden_after)}")

    # Show diff
    if golden_before and golden_after:
        if golden_before["row_hash"] != golden_after.get("row_hash"):
            print("\n  --- Changes ---")
            for field in ["first_name", "last_name", "email", "phone", "dq_score", "source_count"]:
                old = golden_before.get(field)
                new = golden_after.get(field)
                if old != new:
                    print(f"    {field}: {old} -> {new}")
        else:
            print("    (no change in golden attributes)")

    # Collect CDC events
    print(f"\n  --- CDC Kafka Events ---")
    cdc_events = []
    deadline = time.time() + 8.0
    while time.time() < deadline:
        msg = cdc_consumer.poll(timeout=1.0)
        if msg is None:
            continue
        if msg.error():
            continue
        try:
            evt = json.loads(msg.value())
            evt["_topic"] = msg.topic()
            cdc_events.append(evt)
        except (json.JSONDecodeError, TypeError):
            pass
    cdc_consumer.close()

    if not cdc_events:
        print("    (none captured)")
    for evt in cdc_events:
        t = evt.pop("_topic", "")
        topic_label = "golden" if t == GOLDEN_TOPIC else "xref"
        print(f"    [{topic_label}] {json.dumps(evt, indent=None)}")

    # =========================================================================
    # Validation
    # =========================================================================
    print(f"\n{'=' * 70}")
    errors = []

    if golden_after is None:
        errors.append("FAIL: No golden record found after update")
    elif golden_before and golden_after:
        # Golden should still exist and be valid
        if golden_after["dq_score"] is None or golden_after["dq_score"] < 0:
            errors.append(f"FAIL: Invalid DQ score: {golden_after['dq_score']}")

    if golden_count < 100:
        errors.append(f"FAIL: Too few golden records: {golden_count}")

    if errors:
        print(f"RESULT: FAILED ({len(errors)} errors)")
        for e in errors:
            print(f"  {e}")
        sys.exit(1)
    else:
        print("RESULT: ALL CHECKS PASSED")
        print(f"  Golden records: {golden_count}")
        print(f"  Update processed for cluster {cluster_id}")
        sys.exit(0)


if __name__ == "__main__":
    main()
