-- =============================================================================
-- post_deploy.sql — Objects not supported by DEFINE (streams, file formats, tasks)
-- =============================================================================
-- Run after: snow dcm deploy
-- Execution: snow sql -f post_deploy.sql --enable-templating JINJA \
--   -D db=MDM_DEV -D raw_schema=MDM_RAW_v001 -D agg_schema=MDM_AGG_v001 \
--   -c <connection>
-- =============================================================================

USE DATABASE {{ db }};
USE SCHEMA {{ raw_schema }};

-- File Formats
CREATE OR REPLACE FILE FORMAT CRMI_RAW_FF_FREG  TYPE='CSV' FIELD_DELIMITER=',' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' NULL_IF=('','NULL','null')       EMPTY_FIELD_AS_NULL=TRUE ENCODING='UTF8';
CREATE OR REPLACE FILE FORMAT CRMI_RAW_FF_BS    TYPE='CSV' FIELD_DELIMITER=',' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' NULL_IF=('','NULL','null')       EMPTY_FIELD_AS_NULL=TRUE ENCODING='UTF8';
CREATE OR REPLACE FILE FORMAT CRMI_RAW_FF_NICE  TYPE='CSV' FIELD_DELIMITER=',' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' NULL_IF=('','NULL','null','N/A') EMPTY_FIELD_AS_NULL=TRUE ENCODING='UTF8';
CREATE OR REPLACE FILE FORMAT CRMI_RAW_FF_ADDRESSES_FREG TYPE='CSV' FIELD_DELIMITER=',' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' NULL_IF=('','NULL','null')       EMPTY_FIELD_AS_NULL=TRUE ENCODING='UTF8';
CREATE OR REPLACE FILE FORMAT CRMI_RAW_FF_ADDRESSES_BS   TYPE='CSV' FIELD_DELIMITER=',' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' NULL_IF=('','NULL','null')       EMPTY_FIELD_AS_NULL=TRUE ENCODING='UTF8';
CREATE OR REPLACE FILE FORMAT CRMI_RAW_FF_ADDRESSES_NICE TYPE='CSV' FIELD_DELIMITER=',' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' NULL_IF=('','NULL','null','N/A') EMPTY_FIELD_AS_NULL=TRUE ENCODING='UTF8';

-- Streams on directory tables
CREATE OR REPLACE STREAM CRMI_RAW_SM_FREG            ON STAGE CRMI_RAW_ST_FREG;
CREATE OR REPLACE STREAM CRMI_RAW_SM_BS              ON STAGE CRMI_RAW_ST_BS;
CREATE OR REPLACE STREAM CRMI_RAW_SM_NICE            ON STAGE CRMI_RAW_ST_NICE;
CREATE OR REPLACE STREAM CRMI_RAW_SM_ADDRESSES_FREG  ON STAGE CRMI_RAW_ST_ADDRESSES_FREG;
CREATE OR REPLACE STREAM CRMI_RAW_SM_ADDRESSES_BS    ON STAGE CRMI_RAW_ST_ADDRESSES_BS;
CREATE OR REPLACE STREAM CRMI_RAW_SM_ADDRESSES_NICE  ON STAGE CRMI_RAW_ST_ADDRESSES_NICE;

-- Serverless tasks (event-driven ingestion)
-- FREG: SSN, First_Name, Last_Name, Birth_Date, Citizenship, Record_Date, _SOURCE_FILE
CREATE OR REPLACE TASK CRMI_RAW_TS_LOAD_FREG
    SCHEDULE = '60 MINUTE' USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
    WHEN SYSTEM$STREAM_HAS_DATA('CRMI_RAW_SM_FREG')
AS COPY INTO CRMI_RAW_TB_FREG (SSN, FIRST_NAME, LAST_NAME, BIRTH_DATE, CITIZENSHIP, RECORD_DATE, _SOURCE_FILE)
    FROM (SELECT $1, $2, $3, $4::DATE, $5, $6::DATE, METADATA$FILENAME FROM @CRMI_RAW_ST_FREG)
    FILE_FORMAT = CRMI_RAW_FF_FREG ON_ERROR = 'CONTINUE';

-- BS: SSN, First_Name, Last_Name, Phone, Email, Record_Date, Organization, _SOURCE_FILE
CREATE OR REPLACE TASK CRMI_RAW_TS_LOAD_BS
    SCHEDULE = '60 MINUTE' USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
    WHEN SYSTEM$STREAM_HAS_DATA('CRMI_RAW_SM_BS')
AS COPY INTO CRMI_RAW_TB_BS (SSN, FIRST_NAME, LAST_NAME, PHONE, EMAIL, RECORD_DATE, ORGANIZATION, _SOURCE_FILE)
    FROM (SELECT $1, $2, $3, $4, $5, $6::DATE, $7, METADATA$FILENAME FROM @CRMI_RAW_ST_BS)
    FILE_FORMAT = CRMI_RAW_FF_BS ON_ERROR = 'CONTINUE';

-- NICE: SSN (nullable), First_Name, Last_Name, Phone, Email, Record_Date, Organization, _SOURCE_FILE
CREATE OR REPLACE TASK CRMI_RAW_TS_LOAD_NICE
    SCHEDULE = '60 MINUTE' USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
    WHEN SYSTEM$STREAM_HAS_DATA('CRMI_RAW_SM_NICE')
AS COPY INTO CRMI_RAW_TB_NICE (SSN, FIRST_NAME, LAST_NAME, PHONE, EMAIL, RECORD_DATE, ORGANIZATION, _SOURCE_FILE)
    FROM (SELECT $1, $2, $3, $4, $5, $6::DATE, $7, METADATA$FILENAME FROM @CRMI_RAW_ST_NICE)
    FILE_FORMAT = CRMI_RAW_FF_NICE ON_ERROR = 'CONTINUE';

-- Addresses: SRC_ADDRESS_ID, SRC_CUSTOMER_ID, GATE, POSTNUMMER, "BY", LAND, _SOURCE_FILE
CREATE OR REPLACE TASK CRMI_RAW_TS_LOAD_ADDRESSES_FREG
    SCHEDULE = '60 MINUTE' USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
    WHEN SYSTEM$STREAM_HAS_DATA('CRMI_RAW_SM_ADDRESSES_FREG')
AS COPY INTO CRMI_RAW_TB_ADDRESSES_FREG (SRC_ADDRESS_ID, SRC_CUSTOMER_ID, GATE, POSTNUMMER, "BY", LAND, _SOURCE_FILE)
    FROM (SELECT $1, $2, $3, $4, $5, $6, METADATA$FILENAME FROM @CRMI_RAW_ST_ADDRESSES_FREG)
    FILE_FORMAT = CRMI_RAW_FF_ADDRESSES_FREG ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK CRMI_RAW_TS_LOAD_ADDRESSES_BS
    SCHEDULE = '60 MINUTE' USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
    WHEN SYSTEM$STREAM_HAS_DATA('CRMI_RAW_SM_ADDRESSES_BS')
AS COPY INTO CRMI_RAW_TB_ADDRESSES_BS (SRC_ADDRESS_ID, SRC_CUSTOMER_ID, GATE, POSTNUMMER, "BY", LAND, _SOURCE_FILE)
    FROM (SELECT $1, $2, $3, $4, $5, $6, METADATA$FILENAME FROM @CRMI_RAW_ST_ADDRESSES_BS)
    FILE_FORMAT = CRMI_RAW_FF_ADDRESSES_BS ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK CRMI_RAW_TS_LOAD_ADDRESSES_NICE
    SCHEDULE = '60 MINUTE' USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
    WHEN SYSTEM$STREAM_HAS_DATA('CRMI_RAW_SM_ADDRESSES_NICE')
AS COPY INTO CRMI_RAW_TB_ADDRESSES_NICE (SRC_ADDRESS_ID, SRC_CUSTOMER_ID, GATE, POSTNUMMER, "BY", LAND, _SOURCE_FILE)
    FROM (SELECT $1, $2, $3, $4, $5, $6, METADATA$FILENAME FROM @CRMI_RAW_ST_ADDRESSES_NICE)
    FILE_FORMAT = CRMI_RAW_FF_ADDRESSES_NICE ON_ERROR = 'CONTINUE';

-- Unmerge override table for Scenario 5 (POC demo)
-- Groups DT reads this table and excludes matching pairs via LEFT ANTI JOIN
CREATE TABLE IF NOT EXISTS {{ db }}.{{ agg_schema }}.CRMA_AGG_TB_UNMERGE_OVERRIDES (
    SOURCE_KEY_A VARCHAR(100),
    SOURCE_KEY_B VARCHAR(100),
    REASON       VARCHAR(500),
    CREATED_AT   TIMESTAMP_NTZ DEFAULT SYSDATE(),
    CREATED_BY   VARCHAR(100)
);

-- Resume tasks
ALTER TASK CRMI_RAW_TS_LOAD_FREG           RESUME;
ALTER TASK CRMI_RAW_TS_LOAD_BS             RESUME;
ALTER TASK CRMI_RAW_TS_LOAD_NICE           RESUME;
ALTER TASK CRMI_RAW_TS_LOAD_ADDRESSES_FREG RESUME;
ALTER TASK CRMI_RAW_TS_LOAD_ADDRESSES_BS   RESUME;
ALTER TASK CRMI_RAW_TS_LOAD_ADDRESSES_NICE RESUME;
